#!/bin/bash
#Execute manually unrolled targets
make bench_conflict_detection_unrolled_and_aggregate_ui64_VL512 >> ./build/build_conflict_detection_unrolled_and_aggregate_ui64_VL512.log 2>&1
make bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K >> ./build/build_conflict_detection_unrolled_and_aggregate_ui64_VL1K.log 2>&1
make bench_conflict_detection_unrolled_and_aggregate_ui32_VL512 >> ./build/build_conflict_detection_unrolled_and_aggregate_ui32_VL512.log 2>&1

#Execute make for combined targets
make bench_aggregate_plain_bigint >> ./build/build_aggregate_plain_bigint.log 2>&1
make bench_aggregate_plain_smallint >> ./build/build_aggregate_plain_smallint.log 2>&1
make bench_aggregate_autovec_smallint_VL128_to_512 >> ./build/build_aggregate_autovec_smallint_VL128_to_512.log 2>&1
make bench_aggregate_autovec_smallint_VL1K_to_4K >> ./build/build_aggregate_autovec_smallint_VL1K_to_4K.log 2>&1
make bench_aggregate_autovec_bigint_VL128_to_512 >> ./build/build_aggregate_autovec_bigint_VL128_to_512.log 2>&1
make bench_aggregate_autovec_bigint_VL1K_to_4K >> ./build/build_aggregate_autovec_bigint_VL1K_to_4K.log 2>&1
make bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.log 2>&1
make bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K >> ./build/build_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.log 2>&1
make bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.log 2>&1
make bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K >> ./build/build_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.log 2>&1
make bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512 >> ./build/build_modulo_and_aggregate_outDevice_smallint_VL128_to_512.log 2>&1
make bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K >> ./build/build_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.log 2>&1
make bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512 >> ./build/build_modulo_and_aggregate_outDevice_bigint_VL128_to_512.log 2>&1
make bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K >> ./build/build_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.log 2>&1
make bench_hadd_smallint_VL128_to_512 >> ./build/build_hadd_smallint_VL128_to_512.log 2>&1
make bench_hadd_smallint_VL1K_to_4K >> ./build/build_hadd_smallint_VL1K_to_4K.log 2>&1
make bench_hadd_bigint_VL128_to_512 >> ./build/build_hadd_bigint_VL128_to_512.log 2>&1
make bench_hadd_bigint_VL1K_to_4K >> ./build/build_hadd_bigint_VL1K_to_4K.log 2>&1

#Execute make for special targets (use them if design is to big to fit)
##########################################################################################################
#make bench_aggregate_autovec_smallint_VL128 >> ./build/build_aggregate_autovec_smallint_VL128.log 2>&1
#make bench_aggregate_autovec_smallint_VL256 >> ./build/build_aggregate_autovec_smallint_VL256.log 2>&1
#make bench_aggregate_autovec_smallint_VL512 >> ./build/build_aggregate_autovec_smallint_VL512.log 2>&1
#make bench_aggregate_autovec_smallint_VL1k >> ./build/build_aggregate_autovec_smallint_VL1k.log 2>&1
#make bench_aggregate_autovec_smallint_VL2k >> ./build/build_aggregate_autovec_smallint_VL2k.log 2>&1
#make bench_aggregate_autovec_smallint_VL4k >> ./build/build_aggregate_autovec_smallint_VL4k.log 2>&1
#make bench_aggregate_autovec_bigint_VL128 >> ./build/build_aggregate_autovec_bigint_VL128.log 2>&1
#make bench_aggregate_autovec_bigint_VL256 >> ./build/build_aggregate_autovec_bigint_VL256.log 2>&1
#make bench_aggregate_autovec_bigint_VL512 >> ./build/build_aggregate_autovec_bigint_VL512.log 2>&1
#make bench_aggregate_autovec_bigint_VL1k >> ./build/build_aggregate_autovec_bigint_VL1k.log 2>&1
#make bench_aggregate_autovec_bigint_VL2k >> ./build/build_aggregate_autovec_bigint_VL2k.log 2>&1
#make bench_aggregate_autovec_bigint_VL4k >> ./build/build_aggregate_autovec_bigint_VL4k.log 2>&1
#make bench_aggregate_autovec_ui8_VL128_to_512 >> ./build/build_aggregate_autovec_ui8_VL128_to_512.log 2>&1
#make bench_aggregate_autovec_ui8_VL1K_to_4K >> ./build/build_aggregate_autovec_ui8_VL1K_to_4K.log 2>&1
#make bench_aggregate_autovec_ui8_VL128 >> ./build/build_aggregate_autovec_ui8_VL128.log 2>&1
#make bench_aggregate_autovec_ui8_VL256 >> ./build/build_aggregate_autovec_ui8_VL256.log 2>&1
#make bench_aggregate_autovec_ui8_VL512 >> ./build/build_aggregate_autovec_ui8_VL512.log 2>&1
#make bench_aggregate_autovec_ui8_VL1k >> ./build/build_aggregate_autovec_ui8_VL1k.log 2>&1
#make bench_aggregate_autovec_ui8_VL2k >> ./build/build_aggregate_autovec_ui8_VL2k.log 2>&1
#make bench_aggregate_autovec_ui8_VL4k >> ./build/build_aggregate_autovec_ui8_VL4k.log 2>&1
#make bench_aggregate_autovec_ui16_VL128_to_512 >> ./build/build_aggregate_autovec_ui16_VL128_to_512.log 2>&1
#make bench_aggregate_autovec_ui16_VL1K_to_4K >> ./build/build_aggregate_autovec_ui16_VL1K_to_4K.log 2>&1
#make bench_aggregate_autovec_ui16_VL128 >> ./build/build_aggregate_autovec_ui16_VL128.log 2>&1
#make bench_aggregate_autovec_ui16_VL256 >> ./build/build_aggregate_autovec_ui16_VL256.log 2>&1
#make bench_aggregate_autovec_ui16_VL512 >> ./build/build_aggregate_autovec_ui16_VL512.log 2>&1
#make bench_aggregate_autovec_ui16_VL1k >> ./build/build_aggregate_autovec_ui16_VL1k.log 2>&1
#make bench_aggregate_autovec_ui16_VL2k >> ./build/build_aggregate_autovec_ui16_VL2k.log 2>&1
#make bench_aggregate_autovec_ui16_VL4k >> ./build/build_aggregate_autovec_ui16_VL4k.log 2>&1
#make bench_aggregate_autovec_ui32_VL128_to_512 >> ./build/build_aggregate_autovec_ui32_VL128_to_512.log 2>&1
#make bench_aggregate_autovec_ui32_VL1K_to_4K >> ./build/build_aggregate_autovec_ui32_VL1K_to_4K.log 2>&1
#make bench_aggregate_autovec_ui32_VL128 >> ./build/build_aggregate_autovec_ui32_VL128.log 2>&1
#make bench_aggregate_autovec_ui32_VL256 >> ./build/build_aggregate_autovec_ui32_VL256.log 2>&1
#make bench_aggregate_autovec_ui32_VL512 >> ./build/build_aggregate_autovec_ui32_VL512.log 2>&1
#make bench_aggregate_autovec_ui32_VL1k >> ./build/build_aggregate_autovec_ui32_VL1k.log 2>&1
#make bench_aggregate_autovec_ui32_VL2k >> ./build/build_aggregate_autovec_ui32_VL2k.log 2>&1
#make bench_aggregate_autovec_ui32_VL4k >> ./build/build_aggregate_autovec_ui32_VL4k.log 2>&1
#make bench_aggregate_autovec_ui64_VL128_to_512 >> ./build/build_aggregate_autovec_ui64_VL128_to_512.log 2>&1
#make bench_aggregate_autovec_ui64_VL1K_to_4K >> ./build/build_aggregate_autovec_ui64_VL1K_to_4K.log 2>&1
#make bench_aggregate_autovec_ui64_VL128 >> ./build/build_aggregate_autovec_ui64_VL128.log 2>&1
#make bench_aggregate_autovec_ui64_VL256 >> ./build/build_aggregate_autovec_ui64_VL256.log 2>&1
#make bench_aggregate_autovec_ui64_VL512 >> ./build/build_aggregate_autovec_ui64_VL512.log 2>&1
#make bench_aggregate_autovec_ui64_VL1k >> ./build/build_aggregate_autovec_ui64_VL1k.log 2>&1
#make bench_aggregate_autovec_ui64_VL2k >> ./build/build_aggregate_autovec_ui64_VL2k.log 2>&1
#make bench_aggregate_autovec_ui64_VL4k >> ./build/build_aggregate_autovec_ui64_VL4k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_smallint_VL128.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL256 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_smallint_VL256.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_smallint_VL512.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_smallint_VL1k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL2k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_smallint_VL2k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL4k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_smallint_VL4k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_bigint_VL128.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL256 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_bigint_VL256.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_bigint_VL512.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_bigint_VL1k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL2k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_bigint_VL2k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL4k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_bigint_VL4k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui8_VL128_to_512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui8_VL128_to_512.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui8_VL1K_to_4K >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui8_VL1K_to_4K.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui8_VL128 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui8_VL128.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui8_VL256 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui8_VL256.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui8_VL512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui8_VL512.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui8_VL1k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui8_VL1k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui8_VL2k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui8_VL2k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui8_VL4k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui8_VL4k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui16_VL128_to_512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui16_VL128_to_512.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui16_VL1K_to_4K >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui16_VL1K_to_4K.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui16_VL128 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui16_VL128.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui16_VL256 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui16_VL256.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui16_VL512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui16_VL512.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui16_VL1k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui16_VL1k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui16_VL2k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui16_VL2k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui16_VL4k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui16_VL4k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui32_VL128_to_512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui32_VL128_to_512.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui32_VL1K_to_4K >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui32_VL1K_to_4K.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui32_VL128 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui32_VL128.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui32_VL256 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui32_VL256.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui32_VL512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui32_VL512.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui32_VL1k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui32_VL1k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui32_VL2k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui32_VL2k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui32_VL4k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui32_VL4k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui64_VL128_to_512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui64_VL128_to_512.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui64_VL1K_to_4K >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui64_VL1K_to_4K.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui64_VL128 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui64_VL128.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui64_VL256 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui64_VL256.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui64_VL512 >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui64_VL512.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui64_VL1k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui64_VL1k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui64_VL2k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui64_VL2k.log 2>&1
#make bench_lzc_unrolled_and_aggregate_outDevice_ui64_VL4k >> ./build/build_lzc_unrolled_and_aggregate_outDevice_ui64_VL4k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_smallint_VL128 >> ./build/build_modulo_and_aggregate_outDevice_smallint_VL128.log 2>&1
#make bench_modulo_and_aggregate_outDevice_smallint_VL256 >> ./build/build_modulo_and_aggregate_outDevice_smallint_VL256.log 2>&1
#make bench_modulo_and_aggregate_outDevice_smallint_VL512 >> ./build/build_modulo_and_aggregate_outDevice_smallint_VL512.log 2>&1
#make bench_modulo_and_aggregate_outDevice_smallint_VL1k >> ./build/build_modulo_and_aggregate_outDevice_smallint_VL1k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_smallint_VL2k >> ./build/build_modulo_and_aggregate_outDevice_smallint_VL2k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_smallint_VL4k >> ./build/build_modulo_and_aggregate_outDevice_smallint_VL4k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_bigint_VL128 >> ./build/build_modulo_and_aggregate_outDevice_bigint_VL128.log 2>&1
#make bench_modulo_and_aggregate_outDevice_bigint_VL256 >> ./build/build_modulo_and_aggregate_outDevice_bigint_VL256.log 2>&1
#make bench_modulo_and_aggregate_outDevice_bigint_VL512 >> ./build/build_modulo_and_aggregate_outDevice_bigint_VL512.log 2>&1
#make bench_modulo_and_aggregate_outDevice_bigint_VL1k >> ./build/build_modulo_and_aggregate_outDevice_bigint_VL1k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_bigint_VL2k >> ./build/build_modulo_and_aggregate_outDevice_bigint_VL2k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_bigint_VL4k >> ./build/build_modulo_and_aggregate_outDevice_bigint_VL4k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui8_VL128_to_512 >> ./build/build_modulo_and_aggregate_outDevice_ui8_VL128_to_512.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui8_VL1K_to_4K >> ./build/build_modulo_and_aggregate_outDevice_ui8_VL1K_to_4K.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui8_VL128 >> ./build/build_modulo_and_aggregate_outDevice_ui8_VL128.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui8_VL256 >> ./build/build_modulo_and_aggregate_outDevice_ui8_VL256.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui8_VL512 >> ./build/build_modulo_and_aggregate_outDevice_ui8_VL512.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui8_VL1k >> ./build/build_modulo_and_aggregate_outDevice_ui8_VL1k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui8_VL2k >> ./build/build_modulo_and_aggregate_outDevice_ui8_VL2k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui8_VL4k >> ./build/build_modulo_and_aggregate_outDevice_ui8_VL4k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui16_VL128_to_512 >> ./build/build_modulo_and_aggregate_outDevice_ui16_VL128_to_512.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui16_VL1K_to_4K >> ./build/build_modulo_and_aggregate_outDevice_ui16_VL1K_to_4K.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui16_VL128 >> ./build/build_modulo_and_aggregate_outDevice_ui16_VL128.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui16_VL256 >> ./build/build_modulo_and_aggregate_outDevice_ui16_VL256.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui16_VL512 >> ./build/build_modulo_and_aggregate_outDevice_ui16_VL512.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui16_VL1k >> ./build/build_modulo_and_aggregate_outDevice_ui16_VL1k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui16_VL2k >> ./build/build_modulo_and_aggregate_outDevice_ui16_VL2k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui16_VL4k >> ./build/build_modulo_and_aggregate_outDevice_ui16_VL4k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui32_VL128_to_512 >> ./build/build_modulo_and_aggregate_outDevice_ui32_VL128_to_512.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui32_VL1K_to_4K >> ./build/build_modulo_and_aggregate_outDevice_ui32_VL1K_to_4K.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui32_VL128 >> ./build/build_modulo_and_aggregate_outDevice_ui32_VL128.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui32_VL256 >> ./build/build_modulo_and_aggregate_outDevice_ui32_VL256.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui32_VL512 >> ./build/build_modulo_and_aggregate_outDevice_ui32_VL512.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui32_VL1k >> ./build/build_modulo_and_aggregate_outDevice_ui32_VL1k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui32_VL2k >> ./build/build_modulo_and_aggregate_outDevice_ui32_VL2k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui32_VL4k >> ./build/build_modulo_and_aggregate_outDevice_ui32_VL4k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui64_VL128_to_512 >> ./build/build_modulo_and_aggregate_outDevice_ui64_VL128_to_512.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui64_VL1K_to_4K >> ./build/build_modulo_and_aggregate_outDevice_ui64_VL1K_to_4K.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui64_VL128 >> ./build/build_modulo_and_aggregate_outDevice_ui64_VL128.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui64_VL256 >> ./build/build_modulo_and_aggregate_outDevice_ui64_VL256.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui64_VL512 >> ./build/build_modulo_and_aggregate_outDevice_ui64_VL512.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui64_VL1k >> ./build/build_modulo_and_aggregate_outDevice_ui64_VL1k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui64_VL2k >> ./build/build_modulo_and_aggregate_outDevice_ui64_VL2k.log 2>&1
#make bench_modulo_and_aggregate_outDevice_ui64_VL4k >> ./build/build_modulo_and_aggregate_outDevice_ui64_VL4k.log 2>&1
#make bench_hadd_smallint_VL128 >> ./build/build_hadd_smallint_VL128.log 2>&1
#make bench_hadd_smallint_VL256 >> ./build/build_hadd_smallint_VL256.log 2>&1
#make bench_hadd_smallint_VL512 >> ./build/build_hadd_smallint_VL512.log 2>&1
#make bench_hadd_smallint_VL1k >> ./build/build_hadd_smallint_VL1k.log 2>&1
#make bench_hadd_smallint_VL2k >> ./build/build_hadd_smallint_VL2k.log 2>&1
#make bench_hadd_smallint_VL4k >> ./build/build_hadd_smallint_VL4k.log 2>&1
#make bench_hadd_bigint_VL128 >> ./build/build_hadd_bigint_VL128.log 2>&1
#make bench_hadd_bigint_VL256 >> ./build/build_hadd_bigint_VL256.log 2>&1
#make bench_hadd_bigint_VL512 >> ./build/build_hadd_bigint_VL512.log 2>&1
#make bench_hadd_bigint_VL1k >> ./build/build_hadd_bigint_VL1k.log 2>&1
#make bench_hadd_bigint_VL2k >> ./build/build_hadd_bigint_VL2k.log 2>&1
#make bench_hadd_bigint_VL4k >> ./build/build_hadd_bigint_VL4k.log 2>&1
#make bench_hadd_ui8_VL128_to_512 >> ./build/build_hadd_ui8_VL128_to_512.log 2>&1
#make bench_hadd_ui8_VL1K_to_4K >> ./build/build_hadd_ui8_VL1K_to_4K.log 2>&1
#make bench_hadd_ui8_VL128 >> ./build/build_hadd_ui8_VL128.log 2>&1
#make bench_hadd_ui8_VL256 >> ./build/build_hadd_ui8_VL256.log 2>&1
#make bench_hadd_ui8_VL512 >> ./build/build_hadd_ui8_VL512.log 2>&1
#make bench_hadd_ui8_VL1k >> ./build/build_hadd_ui8_VL1k.log 2>&1
#make bench_hadd_ui8_VL2k >> ./build/build_hadd_ui8_VL2k.log 2>&1
#make bench_hadd_ui8_VL4k >> ./build/build_hadd_ui8_VL4k.log 2>&1
#make bench_hadd_ui16_VL128_to_512 >> ./build/build_hadd_ui16_VL128_to_512.log 2>&1
#make bench_hadd_ui16_VL1K_to_4K >> ./build/build_hadd_ui16_VL1K_to_4K.log 2>&1
#make bench_hadd_ui16_VL128 >> ./build/build_hadd_ui16_VL128.log 2>&1
#make bench_hadd_ui16_VL256 >> ./build/build_hadd_ui16_VL256.log 2>&1
#make bench_hadd_ui16_VL512 >> ./build/build_hadd_ui16_VL512.log 2>&1
#make bench_hadd_ui16_VL1k >> ./build/build_hadd_ui16_VL1k.log 2>&1
#make bench_hadd_ui16_VL2k >> ./build/build_hadd_ui16_VL2k.log 2>&1
#make bench_hadd_ui16_VL4k >> ./build/build_hadd_ui16_VL4k.log 2>&1
#make bench_hadd_ui32_VL128_to_512 >> ./build/build_hadd_ui32_VL128_to_512.log 2>&1
#make bench_hadd_ui32_VL1K_to_4K >> ./build/build_hadd_ui32_VL1K_to_4K.log 2>&1
#make bench_hadd_ui32_VL128 >> ./build/build_hadd_ui32_VL128.log 2>&1
#make bench_hadd_ui32_VL256 >> ./build/build_hadd_ui32_VL256.log 2>&1
#make bench_hadd_ui32_VL512 >> ./build/build_hadd_ui32_VL512.log 2>&1
#make bench_hadd_ui32_VL1k >> ./build/build_hadd_ui32_VL1k.log 2>&1
#make bench_hadd_ui32_VL2k >> ./build/build_hadd_ui32_VL2k.log 2>&1
#make bench_hadd_ui32_VL4k >> ./build/build_hadd_ui32_VL4k.log 2>&1
#make bench_hadd_ui64_VL128_to_512 >> ./build/build_hadd_ui64_VL128_to_512.log 2>&1
#make bench_hadd_ui64_VL1K_to_4K >> ./build/build_hadd_ui64_VL1K_to_4K.log 2>&1
#make bench_hadd_ui64_VL128 >> ./build/build_hadd_ui64_VL128.log 2>&1
#make bench_hadd_ui64_VL256 >> ./build/build_hadd_ui64_VL256.log 2>&1
#make bench_hadd_ui64_VL512 >> ./build/build_hadd_ui64_VL512.log 2>&1
#make bench_hadd_ui64_VL1k >> ./build/build_hadd_ui64_VL1k.log 2>&1
#make bench_hadd_ui64_VL2k >> ./build/build_hadd_ui64_VL2k.log 2>&1
#make bench_hadd_ui64_VL4k >> ./build/build_hadd_ui64_VL4k.log 2>&1
