#!/bin/bash
CWD=$(pwd)
cd ${CWD}/build
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${CWD}/build
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 1MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 2MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 4MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 8MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 16MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 32MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 64MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 128MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 256MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 512MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL512.fpga --size 1GiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 1MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 2MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 4MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 8MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 16MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 32MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 64MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 128MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 256MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 512MiB
./bench_conflict_detection_unrolled_and_aggregate_ui64_VL1K.fpga --size 1GiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 1MiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 2MiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 4MiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 8MiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 16MiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 32MiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 64MiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 128MiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 256MiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 512MiB
./bench_conflict_detection_unrolled_and_aggregate_ui32_VL512.fpga --size 1GiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 1MiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 2MiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 4MiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 8MiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 16MiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 32MiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 64MiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 128MiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 256MiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 512MiB
./bench_aggregate_autovec_smallint_VL128_to_512.fpga --size 1GiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 1MiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 2MiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 4MiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 8MiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 16MiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 32MiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 64MiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 128MiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 256MiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 512MiB
./bench_aggregate_autovec_smallint_VL1K_to_4K.fpga --size 1GiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 1MiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 2MiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 4MiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 8MiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 16MiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 32MiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 64MiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 128MiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 256MiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 512MiB
./bench_aggregate_autovec_bigint_VL128_to_512.fpga --size 1GiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 1MiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 2MiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 4MiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 8MiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 16MiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 32MiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 64MiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 128MiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 256MiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 512MiB
./bench_aggregate_autovec_bigint_VL1K_to_4K.fpga --size 1GiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 1MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 2MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 4MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 8MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 16MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 32MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 64MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 128MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 256MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 512MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 1GiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 1MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 2MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 4MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 8MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 16MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 32MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 64MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 128MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 256MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 512MiB
./bench_lzc_unrolled_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 1GiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 1MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 2MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 4MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 8MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 16MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 32MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 64MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 128MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 256MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 512MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 1GiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 1MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 2MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 4MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 8MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 16MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 32MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 64MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 128MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 256MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 512MiB
./bench_lzc_unrolled_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 1GiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 1MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 2MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 4MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 8MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 16MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 32MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 64MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 128MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 256MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 512MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL128_to_512.fpga --size 1GiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 1MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 2MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 4MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 8MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 16MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 32MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 64MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 128MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 256MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 512MiB
./bench_modulo_and_aggregate_outDevice_smallint_VL1K_to_4K.fpga --size 1GiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 1MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 2MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 4MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 8MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 16MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 32MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 64MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 128MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 256MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 512MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL128_to_512.fpga --size 1GiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 1MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 2MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 4MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 8MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 16MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 32MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 64MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 128MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 256MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 512MiB
./bench_modulo_and_aggregate_outDevice_bigint_VL1K_to_4K.fpga --size 1GiB
./bench_hadd_smallint_VL128_to_512.fpga --size 1MiB
./bench_hadd_smallint_VL128_to_512.fpga --size 2MiB
./bench_hadd_smallint_VL128_to_512.fpga --size 4MiB
./bench_hadd_smallint_VL128_to_512.fpga --size 8MiB
./bench_hadd_smallint_VL128_to_512.fpga --size 16MiB
./bench_hadd_smallint_VL128_to_512.fpga --size 32MiB
./bench_hadd_smallint_VL128_to_512.fpga --size 64MiB
./bench_hadd_smallint_VL128_to_512.fpga --size 128MiB
./bench_hadd_smallint_VL128_to_512.fpga --size 256MiB
./bench_hadd_smallint_VL128_to_512.fpga --size 512MiB
./bench_hadd_smallint_VL128_to_512.fpga --size 1GiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 1MiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 2MiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 4MiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 8MiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 16MiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 32MiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 64MiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 128MiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 256MiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 512MiB
./bench_hadd_smallint_VL1K_to_4K.fpga --size 1GiB
./bench_hadd_bigint_VL128_to_512.fpga --size 1MiB
./bench_hadd_bigint_VL128_to_512.fpga --size 2MiB
./bench_hadd_bigint_VL128_to_512.fpga --size 4MiB
./bench_hadd_bigint_VL128_to_512.fpga --size 8MiB
./bench_hadd_bigint_VL128_to_512.fpga --size 16MiB
./bench_hadd_bigint_VL128_to_512.fpga --size 32MiB
./bench_hadd_bigint_VL128_to_512.fpga --size 64MiB
./bench_hadd_bigint_VL128_to_512.fpga --size 128MiB
./bench_hadd_bigint_VL128_to_512.fpga --size 256MiB
./bench_hadd_bigint_VL128_to_512.fpga --size 512MiB
./bench_hadd_bigint_VL128_to_512.fpga --size 1GiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 1MiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 2MiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 4MiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 8MiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 16MiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 32MiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 64MiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 128MiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 256MiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 512MiB
./bench_hadd_bigint_VL1K_to_4K.fpga --size 1GiB
